name: ScienceHub Board Games

permissions:
  contents: write

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: ['develop']

env:
  NODE_MODULES_PATH: "./node_modules"

jobs:
  create-cache-key:
    name: Create cache key
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.create-cache-key.outputs.key }}
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Output cache key
        id: create-cache-key
        run: echo "key=${{ github.repository }}-${{ github.ref }}-${{ hashFiles('package-lock.json') }}" >> $GITHUB_OUTPUT

  cache-deps:
    name: Cache dependencies
    needs: [create-cache-key]
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Cache (save) node modules
        uses: actions/cache/save@v4
        with:
          path: ${{ env.NODE_MODULES_PATH }}
          key: "${{ needs.create-cache-key.outputs.cache-key }}"

  lint:
    name: Run lint
    needs: [create-cache-key, cache-deps]
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Restore node modules
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.NODE_MODULES_PATH }}
          key: "${{ needs.create-cache-key.outputs.cache-key }}"
          fail-on-cache-miss: true
      - name: Run lint
        run: npm run lint

  stylelint:
    name: Run stylelint
    needs: [create-cache-key, cache-deps]
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Restore node modules
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.NODE_MODULES_PATH }}
          key: "${{ needs.create-cache-key.outputs.cache-key }}"
          fail-on-cache-miss: true
      - name: Run lint
        run: npm run stylelint

  steiger:
    name: Run steiger
    needs: [create-cache-key, cache-deps]
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Restore node modules
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.NODE_MODULES_PATH }}
          key: "${{ needs.create-cache-key.outputs.cache-key }}"
          fail-on-cache-miss: true
      - name: Run steiger
        run: npm run steiger

  build:
    name: Run build
    needs: [create-cache-key, cache-deps, lint, stylelint, steiger]
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Restore node modules
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.NODE_MODULES_PATH }}
          key: "${{ needs.create-cache-key.outputs.cache-key }}"
          fail-on-cache-miss: true
      - name: Run build
        run: npm run build:production

  deploy:
    if: github.event_name == 'push' && github.ref_name == 'develop'
    name: Deploy (GitHub Pages)
    needs: [create-cache-key, cache-deps, lint, stylelint, steiger, build]
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Restore node modules
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.NODE_MODULES_PATH }}
          key: "${{ needs.create-cache-key.outputs.cache-key }}"
          fail-on-cache-miss: true
      - name: Build web app for GitHub Pages
        run: npm run build:production -- --base-href=/science-hub-board-games/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/science-hub-board-games/browser
